# database schema
-- ===========================
-- USERS TABLE
-- ===========================
drop table if exists users;
CREATE TABLE if not exists users (
    id              BIGSERIAL PRIMARY KEY,
    username        VARCHAR(50) UNIQUE,
    email           VARCHAR(255) UNIQUE,
    password_hash   VARCHAR(255), -- nullable
    provider        VARCHAR(50) DEFAULT 'google', -- ex: google, github, apple
    provider_id     VARCHAR(255) UNIQUE, -- external id from oauth
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

insert into users (username, email, password_hash, provider, provider_id)
VALUES ('darkowlrising', 'tio.taek.lim@gmail.com', null, 'google', null);

-- ===========================
-- POSTS TABLE
-- ===========================
CREATE TYPE if not exists post_status_enum AS ENUM ('public', 'private', 'follower');
drop table if exists posts;
CREATE TABLE IF NOT EXISTS posts (
    -- id              BIGSERIAL PRIMARY KEY,
    -- id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    -- id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    user_id         BIGINT NOT NULL,
    title           VARCHAR(255),
    slug            VARCHAR(255) NOT NULL,
    description     TEXT DEFAULT NULL,
    content         TEXT DEFAULT NULL,
    status          post_status_enum NOT NULL DEFAULT 'public',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

-- ===========================
-- FILES TABLE
-- ===========================
drop table if exists files;
CREATE TABLE if not exists files (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    post_id         BIGINT,
    content_type    VARCHAR(100),
    ext             VARCHAR(30),
    original_filename        VARCHAR(255) NOT NULL,
    stored_name     VARCHAR(255) NOT NULL,
    stored_uri      TEXT NOT NULL,
    file_size       INTEGER,
    is_thumbnail    BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL
);

-- ===========================
-- TAGS TABLE
-- ===========================
CREATE TABLE if not exists tags (
    id              BIGSERIAL PRIMARY KEY,
    name            VARCHAR(50) UNIQUE NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL    
);
CREATE INDEX if not exists idx_tags_name ON tags(name);

-- ===========================
-- POST_TAGS (many-to-many)
-- ===========================
drop table if exists post_tags;
CREATE TABLE if not exists post_tags (
    post_id         BIGINT NOT NULL,
    tag_name        VARCHAR(50) UNIQUE NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,    
    PRIMARY KEY (post_id, tag_name)
);

-- ===========================
-- INDEXES
-- ===========================
CREATE INDEX if not exists idx_users_username ON users(username);
CREATE INDEX if not exists idx_users_provider_id ON users(provider_id);
CREATE INDEX if not exists idx_posts_user_id ON posts(user_id);
CREATE INDEX if not exists idx_files_user_id ON files(user_id);
CREATE INDEX if not exists idx_files_post_id ON files(post_id);
CREATE INDEX if not exists idx_post_tags_tag_id ON post_tags(tag_name);
CREATE INDEX if not exists idx_post_tags_post_id ON post_tags(post_id);


-- ===========================
-- categories TABLE
-- ===========================
-- CREATE TABLE categories (
--     id          BIGSERIAL PRIMARY KEY,
--     name        VARCHAR(100) NOT NULL,
--     parent_id   BIGINT REFERENCES categories(id) ON DELETE CASCADE,
--     root_id     BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
--     level       INT NOT NULL DEFAULT 0,
--     UNIQUE(name, parent_id)
-- );

drop table if exists categories;
CREATE TABLE if not exists categories (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    parent_id   BIGINT NOT NULL,
    root_id     BIGINT NOT NULL,
    level       INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,
    UNIQUE(name, parent_id)
);

-- 인덱스
CREATE INDEX if not exists idx_categories_parent_id ON categories(parent_id);
CREATE INDEX if not exists idx_categories_root_id ON categories(root_id);
CREATE INDEX if not exists idx_categories_level ON categories(level);


-- ===========================
-- post_categories TABLE
-- ===========================
-- CREATE TABLE post_categories (
--     post_id     BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
--     category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
--     PRIMARY KEY (post_id, category_id)
-- );
CREATE TABLE if not exists post_categories (
    post_id     BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP DEFAULT NULL,    
    PRIMARY KEY (post_id, category_id)
);

CREATE INDEX if not exists idx_post_categories_category_id ON post_categories(category_id);
CREATE INDEX if not exists idx_post_categories_post_id ON post_categories(post_id);


-- ===========================
-- upsert
-- ===========================

INSERT INTO users (username, email, password_hash)
VALUES ('john', 'john@example.com', 'hashed_pw')
ON CONFLICT (email)
DO UPDATE
SET username = EXCLUDED.username,
    password_hash = EXCLUDED.password_hash,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO users (username, email)
VALUES ('john', 'john@example.com')
ON CONFLICT (email)
DO NOTHING;